# Generated by Django 6.0.2 on 2026-02-28 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupon_and_order_discount'),
        ('products', '0003_remove_stockreservation_unique_active_reservation_per_cart_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_label',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
