# Generated by Django 6.0.2 on 2026-02-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("cart", "0002_guest_cart_support"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="last_out_of_stock_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="last_restocked_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="last_stock_movement_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("RESTOCK", "Restock"),
                            ("SALE", "Sale"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("RESERVATION", "Reservation"),
                            ("RESERVATION_RELEASE", "Reservation Release"),
                            ("RESERVATION_CONSUMED", "Reservation Consumed"),
                            ("RETURN", "Return"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("quantity_delta", models.IntegerField()),
                ("quantity_before", models.PositiveIntegerField()),
                ("quantity_after", models.PositiveIntegerField()),
                ("reference_type", models.CharField(blank=True, default="", max_length=40)),
                ("reference_id", models.CharField(blank=True, default="", max_length=80)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_movements",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["product", "created_at"], name="products_in_product_af8b5f_idx"),
                    models.Index(fields=["movement_type", "created_at"], name="products_in_movemen_be5629_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("color", models.CharField(blank=True, max_length=60)),
                ("size", models.CharField(blank=True, max_length=30)),
                ("sku", models.CharField(blank=True, default="", max_length=64)),
                ("stock_override", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["product_id", "color", "size", "id"],
            },
        ),
        migrations.CreateModel(
            name="StockNotificationSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("channel", models.CharField(choices=[("EMAIL", "Email"), ("WHATSAPP", "WhatsApp")], max_length=20)),
                ("contact_value", models.CharField(max_length=180)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_notifications",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("RELEASED", "Released"), ("CONSUMED", "Consumed"), ("EXPIRED", "Expired")], db_index=True, default="ACTIVE", max_length=20)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_reservations",
                        to="cart.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_reservations",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image_file", models.ImageField(blank=True, null=True, upload_to="products/media/")),
                ("image_url", models.URLField(blank=True)),
                ("alt_text", models.CharField(blank=True, max_length=180)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="products.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(fields=["product", "sort_order"], name="products_pr_product_d02016_idx"),
                    models.Index(fields=["variant", "sort_order"], name="products_pr_variant_024d00_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(fields=("product", "color", "size"), name="unique_product_variant_color_size"),
        ),
        migrations.AddConstraint(
            model_name="stocknotificationsubscription",
            constraint=models.UniqueConstraint(condition=models.Q(("is_active", True)), fields=("product", "channel", "contact_value"), name="unique_active_stock_notification"),
        ),
        migrations.AddConstraint(
            model_name="stockreservation",
            constraint=models.UniqueConstraint(condition=models.Q(("status", "ACTIVE")), fields=("product", "cart"), name="unique_active_reservation_per_cart_product"),
        ),
    ]
