# Generated by Django 6.0.2 on 2026-02-28 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_guest_cart_support'),
        ('orders', '0003_coupon_and_order_discount'),
        ('products', '0002_merchandising_inventory_upgrade'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockreservation',
            name='unique_active_reservation_per_cart_product',
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to='orders.order'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', True), ('status', 'ACTIVE')), fields=('product', 'cart'), name='unique_active_reservation_per_cart_product'),
        ),
    ]
