# Generated by Django 6.0.2 on 2026-02-28 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_unique_cart_product_cartitem_variant_and_more'),
        ('orders', '0004_orderitem_variant_orderitem_variant_label'),
        ('products', '0003_remove_stockreservation_unique_active_reservation_per_cart_product_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockreservation',
            name='unique_active_reservation_per_cart_product',
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to='products.productvariant'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', True), ('status', 'ACTIVE')), fields=('product', 'variant', 'cart'), name='unique_active_reservation_per_cart_product_variant'),
        ),
    ]
