# Generated by Django 6.0.2 on 2026-03-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_stockreservation_unique_active_reservation_per_cart_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='embedding',
            field=models.JSONField(blank=True, help_text='AI vector embedding for similarity search', null=True),
        ),
    ]
