# Generated by Django 6.0.2 on 2026-02-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_event_n_e2acee_idx',
            old_name='analytics_e_event_n_4da5b5_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_source_22e19f_idx',
            old_name='analytics_e_source_1236da_idx',
        ),
    ]
