# Generated by Django 6.0.2 on 2026-02-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0002_userpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="inferred_segment",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("neutral", "Neutral")],
                default="neutral",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="inferred_segment_confidence",
            field=models.FloatField(default=0.0),
        ),
    ]
