# Generated by Django 6.0 on 2026-02-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0004_assistant_chat_session_and_message'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assistantchatmessage',
            new_name='ai_engine_a_session_85c920_idx',
            old_name='ai_engine_as_session_7f6f31_idx',
        ),
    ]
